export const STATUTS_MAP: { [code: number]: string } = {
  1: "Créé",
  2: "Validé",
  3: "Confirmé",
  4: "Annulé",
  5: "Forcé",
  6: "En attente",
  7: "Attente confirmée",
  8: "Rejeté",
  9: "Suspens",
  10: "Ouvert(e)",
  11: "Pré-clôturé(e)",
  12: "Clôturé",
  13: "Satisfait",
  14: "Délivré",
  15: "Remis à l'agence",
  16: "Prêt pour payement",
  17: "Payé",
  18: "Prêt pour comp. émise",
  19: "Emis",
  20: "Reçu",
  21: "Impayé",
  22: "En attente de payement",
  23: "Certifié",
  24: "En opposition",
  25: "Saisie appliquée",
  26: "Saisie levée",
  27: "Gelé",
  28: "Bloqué",
  29: "Levée de suspens",
  30: "Reçu Partiel",
  31: "Sous visa",
  32: "Visa sur Débit",
  33: "Épuisé",
  34: "Main levée",
  35: "Modifié(e)",
  36: "Approuvé",
  37: "Engagé",
  38: "Payé partiellement",
  39: "Reporté",
  40: "En cours",
  41: "Non Obtenu",
  42: "Obtenu",
  43: "Échu",
  44: "Réalisé",
  45: "Non accordé",
  46: "Accordé",
  47: "Exécuté",
  48: "À terme",
  49: "Généré",
  50: "Non apuré",
  51: "Incident de paiement",
  52: "Apurée",
  53: "Sous ARP",
  54: "Arrangement",
  55: "Validité prorogée",
  56: "Montant augmenté",
  57: "Fin de relation",
  58: "Émis pour CMP",
  59: "Partiellement délivré",
  60: "Émis pour SIBTEL",
  61: "Sous Papillon",
  62: "Sous Préavis",
  63: "Sous CNP",
  64: "En cours de création",
  65: "Rejeté par ADT",
  66: "En échec",
  67: "Effets prêt pour sortir",
  68: "Effets sorti",
  69: "Effets réclamés",
  70: "Adjugé",
  71: "Rétrocédé",
  72: "Renonciation",
  73: "Partiellement validée",
  74: "À envoyer vers SMT",
  75: "Carte à SMT pour création",
  76: "Carte reçue du SMT",
  77: "À renouveler",
  78: "À refabriquer",
  79: "Accepté",
  80: "Non accepté",
  81: "Émis pour agence",
  82: "Émis pour siège",
  83: "Chq paiement partiel émis",
  84: "Chq paiement ARP émis",
  85: "Chq représenté émis",
  86: "Carte à SMT pour renouvellement",
  87: "Carte à SMT pour refabrication",
  88: "Carte à SMT pour opposition",
  89: "Émis pour correspondant",
  90: "À recalculer PIN",
  91: "Carte à SMT pour PIN",
  92: "Débloqué",
  93: "Soumis",
  94: "Répondu",
  95: "Carte à SMT pour personnalisation",
  96: "À personnaliser",
  97: "Servi",
  98: "Carte désactivée",
  99: "Demande domiciliation"
  // Ajoute les autres si nécessaire
};
