# DataSource configuration for PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/banque
spring.datasource.username=postgres
spring.datasource.password=2003
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=wOahHq7t3hxVXqL6dQvRjYp2s5v8y/B1E4iMlNoPmSbWcZfTeUgKiAxCzF9DnG
jwt.expiration=86400000
mailing.frontend.activation-url=http://localhost:4200/activate-account

# === GMAIL SMTP ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=molkajridi2003@gmail.com
spring.mail.password=bdowndnmaplzxtxx


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.default-encoding=UTF-8
spring.mail.protocol=smtp

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework=DEBUG
logging.level.com.example=DEBUG
